CREATE TABLE Students (
id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
firstname VARCHAR(30) NOT NULL,
lastname VARCHAR(30) NOT NULL,
email VARCHAR(50),
phonenumber VARCHAR(30) NOT NULL,
grade int 
)


SELECT COUNT(ID) FROM STUDENTS

CREATE TABLE `CINEMA` (
  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `NAME` varchar(20) NOT NULL,
  PRIMARY KEY (`ID`) USING BTREE
)


CREATE TABLE `DIRECTOR` (
  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `NAME` varchar(20) NOT NULL,
  PRIMARY KEY (`ID`) USING BTREE
)

CREATE TABLE `MOVIE` (
  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `NAME` varchar(20) NOT NULL,
  PRIMARY KEY (`ID`) USING BTREE,
  `FK_DIRECTOR_ID` int(10) unsigned,
  FOREIGN KEY(`FK_DIRECTOR_ID`) REFERENCES `DIRECTOR`(`ID`)
)

CREATE TABLE `CINEMA_CONNECTOR_MOVIE` (
  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`ID`) USING BTREE,
  `FK_CINEMA_ID` int(10) unsigned,
  FOREIGN KEY(`FK_CINEMA_ID`) REFERENCES `CINEMA`(`ID`),
  `FK_MOVIE_ID` int(10) unsigned,
  FOREIGN KEY(`FK_MOVIE_ID`) REFERENCES `MOVIE`(`ID`)
)


CREATE TABLE `ACTORS` (
  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `NAME` varchar(20) NOT NULL,
  PRIMARY KEY (`ID`) USING BTREE
)

CREATE TABLE `MOVIE_CONNECTOR_ACTORS` (
  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`ID`) USING BTREE,
  `FK_MOVIE_ID` int(10) unsigned,
  FOREIGN KEY(`FK_MOVIE_ID`) REFERENCES `MOVIE`(`ID`),
  `FK_ACTORS_ID` int(10) unsigned,
  FOREIGN KEY(`FK_ACTORS_ID`) REFERENCES `ACTORS`(`ID`)
)

DROP TABLE `MOVIE`

DROP TABLE `CINEMA_CONNECTOR_MOVIE`

DELETE FROM `CINEMA` where id=2

SELECT * FROM MOVIE


CREATE TABLE `CINEMA_DETAILS` (
  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `CITY` varchar(20) NOT NULL,
  `ADDRESS` varchar(20) NOT NULL,
  `PHONE_NUMBER` varchar(20) NOT NULL,
  PRIMARY KEY (`ID`) USING BTREE,
  `FK_CINEMA_ID` int(10) unsigned,
  FOREIGN KEY(`FK_CINEMA_ID`) REFERENCES `CINEMA`(`ID`)
)